### PR TITLE
Resyncing pilotTools.py with upstream integration.

### PR DESCRIPTION
**Pull request by alexanderrichards**
Also cherrypicking changes from PR https://github.com/DIRACGrid/DIRAC/pull/3352

This closes https://github.com/ic-hep/DIRAC/issues/81

### CODE REVIEW

**Comment by alexanderrichards** [comment]
This updates rel-v6r15 branch with the changes that you made in your pilot_pythonpath_fix branch cherry-picked such that it should should include changes from `integration` but not overwrite your changes in DIRACGrid#3352

**Comment by alexanderrichards** [comment]
ah just noticed that that PR is out of date so I'll have to pull in more from integration. I'll just do that now.

**Comment by alexanderrichards** [comment]
done.

**Comment by sfayer** [comment]
Hi Alex,

This is actually one of the files we're overriding in GridPPDIRAC - Would it be possible for you to move your pull request to that repo?

Regards,
Simon

**Comment by alexanderrichards** [comment]
moved to the above PR

**Pull request closed without merging**
